// Generated by gencpp from file mrs_msgs/BacaProtocol.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_BACAPROTOCOL_H
#define MRS_MSGS_MESSAGE_BACAPROTOCOL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrs_msgs
{
template <class ContainerAllocator>
struct BacaProtocol_
{
  typedef BacaProtocol_<ContainerAllocator> Type;

  BacaProtocol_()
    : stamp()
    , payload()
    , checksum_calculated(0)
    , checksum_received(0)
    , checksum_correct(false)  {
    }
  BacaProtocol_(const ContainerAllocator& _alloc)
    : stamp()
    , payload(_alloc)
    , checksum_calculated(0)
    , checksum_received(0)
    , checksum_correct(false)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _payload_type;
  _payload_type payload;

   typedef uint8_t _checksum_calculated_type;
  _checksum_calculated_type checksum_calculated;

   typedef uint8_t _checksum_received_type;
  _checksum_received_type checksum_received;

   typedef uint8_t _checksum_correct_type;
  _checksum_correct_type checksum_correct;





  typedef boost::shared_ptr< ::mrs_msgs::BacaProtocol_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrs_msgs::BacaProtocol_<ContainerAllocator> const> ConstPtr;

}; // struct BacaProtocol_

typedef ::mrs_msgs::BacaProtocol_<std::allocator<void> > BacaProtocol;

typedef boost::shared_ptr< ::mrs_msgs::BacaProtocol > BacaProtocolPtr;
typedef boost::shared_ptr< ::mrs_msgs::BacaProtocol const> BacaProtocolConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrs_msgs::BacaProtocol_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrs_msgs::BacaProtocol_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrs_msgs::BacaProtocol_<ContainerAllocator1> & lhs, const ::mrs_msgs::BacaProtocol_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.payload == rhs.payload &&
    lhs.checksum_calculated == rhs.checksum_calculated &&
    lhs.checksum_received == rhs.checksum_received &&
    lhs.checksum_correct == rhs.checksum_correct;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrs_msgs::BacaProtocol_<ContainerAllocator1> & lhs, const ::mrs_msgs::BacaProtocol_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::BacaProtocol_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::BacaProtocol_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::BacaProtocol_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::BacaProtocol_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::BacaProtocol_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::BacaProtocol_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrs_msgs::BacaProtocol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab27864d6a028e49646c9087913dde4e";
  }

  static const char* value(const ::mrs_msgs::BacaProtocol_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab27864d6a028e49ULL;
  static const uint64_t static_value2 = 0x646c9087913dde4eULL;
};

template<class ContainerAllocator>
struct DataType< ::mrs_msgs::BacaProtocol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrs_msgs/BacaProtocol";
  }

  static const char* value(const ::mrs_msgs::BacaProtocol_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrs_msgs::BacaProtocol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"uint8[] payload\n"
"uint8 checksum_calculated #useful for debugging\n"
"uint8 checksum_received   #useful for debugging\n"
"bool checksum_correct\n"
;
  }

  static const char* value(const ::mrs_msgs::BacaProtocol_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrs_msgs::BacaProtocol_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.payload);
      stream.next(m.checksum_calculated);
      stream.next(m.checksum_received);
      stream.next(m.checksum_correct);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BacaProtocol_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrs_msgs::BacaProtocol_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrs_msgs::BacaProtocol_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "payload[]" << std::endl;
    for (size_t i = 0; i < v.payload.size(); ++i)
    {
      s << indent << "  payload[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.payload[i]);
    }
    s << indent << "checksum_calculated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.checksum_calculated);
    s << indent << "checksum_received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.checksum_received);
    s << indent << "checksum_correct: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.checksum_correct);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRS_MSGS_MESSAGE_BACAPROTOCOL_H
