// Generated by gencpp from file mrs_msgs/BigDofecArmRequest.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_BIGDOFECARMREQUEST_H
#define MRS_MSGS_MESSAGE_BIGDOFECARMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrs_msgs
{
template <class ContainerAllocator>
struct BigDofecArmRequest_
{
  typedef BigDofecArmRequest_<ContainerAllocator> Type;

  BigDofecArmRequest_()
    : arm(false)  {
    }
  BigDofecArmRequest_(const ContainerAllocator& _alloc)
    : arm(false)  {
  (void)_alloc;
    }



   typedef uint8_t _arm_type;
  _arm_type arm;





  typedef boost::shared_ptr< ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BigDofecArmRequest_

typedef ::mrs_msgs::BigDofecArmRequest_<std::allocator<void> > BigDofecArmRequest;

typedef boost::shared_ptr< ::mrs_msgs::BigDofecArmRequest > BigDofecArmRequestPtr;
typedef boost::shared_ptr< ::mrs_msgs::BigDofecArmRequest const> BigDofecArmRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator1> & lhs, const ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator2> & rhs)
{
  return lhs.arm == rhs.arm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator1> & lhs, const ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ac5db510c2f9135f545febefbebd09b";
  }

  static const char* value(const ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ac5db510c2f9135ULL;
  static const uint64_t static_value2 = 0xf545febefbebd09bULL;
};

template<class ContainerAllocator>
struct DataType< ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrs_msgs/BigDofecArmRequest";
  }

  static const char* value(const ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool arm\n"
;
  }

  static const char* value(const ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BigDofecArmRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrs_msgs::BigDofecArmRequest_<ContainerAllocator>& v)
  {
    s << indent << "arm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.arm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRS_MSGS_MESSAGE_BIGDOFECARMREQUEST_H
