// Generated by gencpp from file mrs_msgs/BumperParamsSrv.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_BUMPERPARAMSSRV_H
#define MRS_MSGS_MESSAGE_BUMPERPARAMSSRV_H

#include <ros/service_traits.h>


#include <mrs_msgs/BumperParamsSrvRequest.h>
#include <mrs_msgs/BumperParamsSrvResponse.h>


namespace mrs_msgs
{

struct BumperParamsSrv
{

typedef BumperParamsSrvRequest Request;
typedef BumperParamsSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BumperParamsSrv
} // namespace mrs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mrs_msgs::BumperParamsSrv > {
  static const char* value()
  {
    return "2b4f2150f024cdd7b51d145eb3b4559b";
  }

  static const char* value(const ::mrs_msgs::BumperParamsSrv&) { return value(); }
};

template<>
struct DataType< ::mrs_msgs::BumperParamsSrv > {
  static const char* value()
  {
    return "mrs_msgs/BumperParamsSrv";
  }

  static const char* value(const ::mrs_msgs::BumperParamsSrv&) { return value(); }
};


// service_traits::MD5Sum< ::mrs_msgs::BumperParamsSrvRequest> should match
// service_traits::MD5Sum< ::mrs_msgs::BumperParamsSrv >
template<>
struct MD5Sum< ::mrs_msgs::BumperParamsSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mrs_msgs::BumperParamsSrv >::value();
  }
  static const char* value(const ::mrs_msgs::BumperParamsSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrs_msgs::BumperParamsSrvRequest> should match
// service_traits::DataType< ::mrs_msgs::BumperParamsSrv >
template<>
struct DataType< ::mrs_msgs::BumperParamsSrvRequest>
{
  static const char* value()
  {
    return DataType< ::mrs_msgs::BumperParamsSrv >::value();
  }
  static const char* value(const ::mrs_msgs::BumperParamsSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mrs_msgs::BumperParamsSrvResponse> should match
// service_traits::MD5Sum< ::mrs_msgs::BumperParamsSrv >
template<>
struct MD5Sum< ::mrs_msgs::BumperParamsSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mrs_msgs::BumperParamsSrv >::value();
  }
  static const char* value(const ::mrs_msgs::BumperParamsSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrs_msgs::BumperParamsSrvResponse> should match
// service_traits::DataType< ::mrs_msgs::BumperParamsSrv >
template<>
struct DataType< ::mrs_msgs::BumperParamsSrvResponse>
{
  static const char* value()
  {
    return DataType< ::mrs_msgs::BumperParamsSrv >::value();
  }
  static const char* value(const ::mrs_msgs::BumperParamsSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MRS_MSGS_MESSAGE_BUMPERPARAMSSRV_H
