// Generated by gencpp from file mrs_msgs/ChangeState.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_CHANGESTATE_H
#define MRS_MSGS_MESSAGE_CHANGESTATE_H

#include <ros/service_traits.h>


#include <mrs_msgs/ChangeStateRequest.h>
#include <mrs_msgs/ChangeStateResponse.h>


namespace mrs_msgs
{

struct ChangeState
{

typedef ChangeStateRequest Request;
typedef ChangeStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeState
} // namespace mrs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mrs_msgs::ChangeState > {
  static const char* value()
  {
    return "e106cc88a1deaecd5961b110a257908e";
  }

  static const char* value(const ::mrs_msgs::ChangeState&) { return value(); }
};

template<>
struct DataType< ::mrs_msgs::ChangeState > {
  static const char* value()
  {
    return "mrs_msgs/ChangeState";
  }

  static const char* value(const ::mrs_msgs::ChangeState&) { return value(); }
};


// service_traits::MD5Sum< ::mrs_msgs::ChangeStateRequest> should match
// service_traits::MD5Sum< ::mrs_msgs::ChangeState >
template<>
struct MD5Sum< ::mrs_msgs::ChangeStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mrs_msgs::ChangeState >::value();
  }
  static const char* value(const ::mrs_msgs::ChangeStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrs_msgs::ChangeStateRequest> should match
// service_traits::DataType< ::mrs_msgs::ChangeState >
template<>
struct DataType< ::mrs_msgs::ChangeStateRequest>
{
  static const char* value()
  {
    return DataType< ::mrs_msgs::ChangeState >::value();
  }
  static const char* value(const ::mrs_msgs::ChangeStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mrs_msgs::ChangeStateResponse> should match
// service_traits::MD5Sum< ::mrs_msgs::ChangeState >
template<>
struct MD5Sum< ::mrs_msgs::ChangeStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mrs_msgs::ChangeState >::value();
  }
  static const char* value(const ::mrs_msgs::ChangeStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrs_msgs::ChangeStateResponse> should match
// service_traits::DataType< ::mrs_msgs::ChangeState >
template<>
struct DataType< ::mrs_msgs::ChangeStateResponse>
{
  static const char* value()
  {
    return DataType< ::mrs_msgs::ChangeState >::value();
  }
  static const char* value(const ::mrs_msgs::ChangeStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MRS_MSGS_MESSAGE_CHANGESTATE_H
