// Generated by gencpp from file mrs_msgs/ChangeAltEstimator.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_CHANGEALTESTIMATOR_H
#define MRS_MSGS_MESSAGE_CHANGEALTESTIMATOR_H

#include <ros/service_traits.h>


#include <mrs_msgs/ChangeAltEstimatorRequest.h>
#include <mrs_msgs/ChangeAltEstimatorResponse.h>


namespace mrs_msgs
{

struct ChangeAltEstimator
{

typedef ChangeAltEstimatorRequest Request;
typedef ChangeAltEstimatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeAltEstimator
} // namespace mrs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mrs_msgs::ChangeAltEstimator > {
  static const char* value()
  {
    return "d44d7ecd4f387249481ad597e7864694";
  }

  static const char* value(const ::mrs_msgs::ChangeAltEstimator&) { return value(); }
};

template<>
struct DataType< ::mrs_msgs::ChangeAltEstimator > {
  static const char* value()
  {
    return "mrs_msgs/ChangeAltEstimator";
  }

  static const char* value(const ::mrs_msgs::ChangeAltEstimator&) { return value(); }
};


// service_traits::MD5Sum< ::mrs_msgs::ChangeAltEstimatorRequest> should match
// service_traits::MD5Sum< ::mrs_msgs::ChangeAltEstimator >
template<>
struct MD5Sum< ::mrs_msgs::ChangeAltEstimatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mrs_msgs::ChangeAltEstimator >::value();
  }
  static const char* value(const ::mrs_msgs::ChangeAltEstimatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrs_msgs::ChangeAltEstimatorRequest> should match
// service_traits::DataType< ::mrs_msgs::ChangeAltEstimator >
template<>
struct DataType< ::mrs_msgs::ChangeAltEstimatorRequest>
{
  static const char* value()
  {
    return DataType< ::mrs_msgs::ChangeAltEstimator >::value();
  }
  static const char* value(const ::mrs_msgs::ChangeAltEstimatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mrs_msgs::ChangeAltEstimatorResponse> should match
// service_traits::MD5Sum< ::mrs_msgs::ChangeAltEstimator >
template<>
struct MD5Sum< ::mrs_msgs::ChangeAltEstimatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mrs_msgs::ChangeAltEstimator >::value();
  }
  static const char* value(const ::mrs_msgs::ChangeAltEstimatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrs_msgs::ChangeAltEstimatorResponse> should match
// service_traits::DataType< ::mrs_msgs::ChangeAltEstimator >
template<>
struct DataType< ::mrs_msgs::ChangeAltEstimatorResponse>
{
  static const char* value()
  {
    return DataType< ::mrs_msgs::ChangeAltEstimator >::value();
  }
  static const char* value(const ::mrs_msgs::ChangeAltEstimatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MRS_MSGS_MESSAGE_CHANGEALTESTIMATOR_H
