// Generated by gencpp from file mrs_msgs/ChangeAltEstimatorResponse.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_CHANGEALTESTIMATORRESPONSE_H
#define MRS_MSGS_MESSAGE_CHANGEALTESTIMATORRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mrs_msgs/AltitudeType.h>

namespace mrs_msgs
{
template <class ContainerAllocator>
struct ChangeAltEstimatorResponse_
{
  typedef ChangeAltEstimatorResponse_<ContainerAllocator> Type;

  ChangeAltEstimatorResponse_()
    : success(false)
    , message()
    , estimator_type()  {
    }
  ChangeAltEstimatorResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , estimator_type(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef  ::mrs_msgs::AltitudeType_<ContainerAllocator>  _estimator_type_type;
  _estimator_type_type estimator_type;





  typedef boost::shared_ptr< ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeAltEstimatorResponse_

typedef ::mrs_msgs::ChangeAltEstimatorResponse_<std::allocator<void> > ChangeAltEstimatorResponse;

typedef boost::shared_ptr< ::mrs_msgs::ChangeAltEstimatorResponse > ChangeAltEstimatorResponsePtr;
typedef boost::shared_ptr< ::mrs_msgs::ChangeAltEstimatorResponse const> ChangeAltEstimatorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator1> & lhs, const ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.estimator_type == rhs.estimator_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator1> & lhs, const ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a942aab46d3e4f0483dd2575ce2a95d3";
  }

  static const char* value(const ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa942aab46d3e4f04ULL;
  static const uint64_t static_value2 = 0x83dd2575ce2a95d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrs_msgs/ChangeAltEstimatorResponse";
  }

  static const char* value(const ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"mrs_msgs/AltitudeType estimator_type\n"
"\n"
"\n"
"================================================================================\n"
"MSG: mrs_msgs/AltitudeType\n"
"uint8 HEIGHT=0\n"
"uint8 PLANE=1\n"
"uint8 BRICK=2\n"
"uint8 VIO=3\n"
"uint8 ALOAM=4\n"
"uint8 ALOAMGARM=5\n"
"uint8 ALOAMREP=6\n"
"uint8 BARO=7\n"
"uint8 RTK=8\n"
"uint8 LIOSAM=9\n"
"\n"
"uint8 TYPE_COUNT=10\n"
"\n"
"string name\n"
"uint8 type\n"
;
  }

  static const char* value(const ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.estimator_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeAltEstimatorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrs_msgs::ChangeAltEstimatorResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "estimator_type: ";
    s << std::endl;
    Printer< ::mrs_msgs::AltitudeType_<ContainerAllocator> >::stream(s, indent + "  ", v.estimator_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRS_MSGS_MESSAGE_CHANGEALTESTIMATORRESPONSE_H
