// Generated by gencpp from file mrs_msgs/ConstraintsOverrideRequest.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_CONSTRAINTSOVERRIDEREQUEST_H
#define MRS_MSGS_MESSAGE_CONSTRAINTSOVERRIDEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrs_msgs
{
template <class ContainerAllocator>
struct ConstraintsOverrideRequest_
{
  typedef ConstraintsOverrideRequest_<ContainerAllocator> Type;

  ConstraintsOverrideRequest_()
    : acceleration_horizontal(0.0)
    , acceleration_vertical(0.0)  {
    }
  ConstraintsOverrideRequest_(const ContainerAllocator& _alloc)
    : acceleration_horizontal(0.0)
    , acceleration_vertical(0.0)  {
  (void)_alloc;
    }



   typedef double _acceleration_horizontal_type;
  _acceleration_horizontal_type acceleration_horizontal;

   typedef double _acceleration_vertical_type;
  _acceleration_vertical_type acceleration_vertical;





  typedef boost::shared_ptr< ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConstraintsOverrideRequest_

typedef ::mrs_msgs::ConstraintsOverrideRequest_<std::allocator<void> > ConstraintsOverrideRequest;

typedef boost::shared_ptr< ::mrs_msgs::ConstraintsOverrideRequest > ConstraintsOverrideRequestPtr;
typedef boost::shared_ptr< ::mrs_msgs::ConstraintsOverrideRequest const> ConstraintsOverrideRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator1> & lhs, const ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator2> & rhs)
{
  return lhs.acceleration_horizontal == rhs.acceleration_horizontal &&
    lhs.acceleration_vertical == rhs.acceleration_vertical;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator1> & lhs, const ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e477e33456dad3e8d818e64f701b2fb3";
  }

  static const char* value(const ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe477e33456dad3e8ULL;
  static const uint64_t static_value2 = 0xd818e64f701b2fb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrs_msgs/ConstraintsOverrideRequest";
  }

  static const char* value(const ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 acceleration_horizontal\n"
"float64 acceleration_vertical\n"
;
  }

  static const char* value(const ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acceleration_horizontal);
      stream.next(m.acceleration_vertical);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConstraintsOverrideRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrs_msgs::ConstraintsOverrideRequest_<ContainerAllocator>& v)
  {
    s << indent << "acceleration_horizontal: ";
    Printer<double>::stream(s, indent + "  ", v.acceleration_horizontal);
    s << indent << "acceleration_vertical: ";
    Printer<double>::stream(s, indent + "  ", v.acceleration_vertical);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRS_MSGS_MESSAGE_CONSTRAINTSOVERRIDEREQUEST_H
