// Generated by gencpp from file mrs_msgs/GazeboAttachRequest.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_GAZEBOATTACHREQUEST_H
#define MRS_MSGS_MESSAGE_GAZEBOATTACHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrs_msgs
{
template <class ContainerAllocator>
struct GazeboAttachRequest_
{
  typedef GazeboAttachRequest_<ContainerAllocator> Type;

  GazeboAttachRequest_()
    : model_name_1()
    , link_name_1()
    , model_name_2()
    , link_name_2()  {
    }
  GazeboAttachRequest_(const ContainerAllocator& _alloc)
    : model_name_1(_alloc)
    , link_name_1(_alloc)
    , model_name_2(_alloc)
    , link_name_2(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _model_name_1_type;
  _model_name_1_type model_name_1;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _link_name_1_type;
  _link_name_1_type link_name_1;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _model_name_2_type;
  _model_name_2_type model_name_2;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _link_name_2_type;
  _link_name_2_type link_name_2;





  typedef boost::shared_ptr< ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GazeboAttachRequest_

typedef ::mrs_msgs::GazeboAttachRequest_<std::allocator<void> > GazeboAttachRequest;

typedef boost::shared_ptr< ::mrs_msgs::GazeboAttachRequest > GazeboAttachRequestPtr;
typedef boost::shared_ptr< ::mrs_msgs::GazeboAttachRequest const> GazeboAttachRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator1> & lhs, const ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator2> & rhs)
{
  return lhs.model_name_1 == rhs.model_name_1 &&
    lhs.link_name_1 == rhs.link_name_1 &&
    lhs.model_name_2 == rhs.model_name_2 &&
    lhs.link_name_2 == rhs.link_name_2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator1> & lhs, const ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff39d0bc8e054b10e21a2f298cb7fb05";
  }

  static const char* value(const ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff39d0bc8e054b10ULL;
  static const uint64_t static_value2 = 0xe21a2f298cb7fb05ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrs_msgs/GazeboAttachRequest";
  }

  static const char* value(const ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A service to apply a force and/or torque to a link in a Gazebo simulation\n"
"# using the mrs_gazebo_ros_interface package. The links will be joined\n"
"# by a revolute joint type.\n"
"\n"
"# Name of the model, containing the first link to be joined.\n"
"string model_name_1\n"
"\n"
"# Name the first link to be joined.\n"
"string link_name_1\n"
"\n"
"# Name of the model, containing the second link to be joined.\n"
"string model_name_2\n"
"\n"
"# Name of the second link to be joined.\n"
"string link_name_2\n"
"\n"
;
  }

  static const char* value(const ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model_name_1);
      stream.next(m.link_name_1);
      stream.next(m.model_name_2);
      stream.next(m.link_name_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GazeboAttachRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrs_msgs::GazeboAttachRequest_<ContainerAllocator>& v)
  {
    s << indent << "model_name_1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.model_name_1);
    s << indent << "link_name_1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.link_name_1);
    s << indent << "model_name_2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.model_name_2);
    s << indent << "link_name_2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.link_name_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRS_MSGS_MESSAGE_GAZEBOATTACHREQUEST_H
