// Generated by gencpp from file mrs_msgs/GazeboDeleteModelRequest.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_GAZEBODELETEMODELREQUEST_H
#define MRS_MSGS_MESSAGE_GAZEBODELETEMODELREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrs_msgs
{
template <class ContainerAllocator>
struct GazeboDeleteModelRequest_
{
  typedef GazeboDeleteModelRequest_<ContainerAllocator> Type;

  GazeboDeleteModelRequest_()
    : model_name()  {
    }
  GazeboDeleteModelRequest_(const ContainerAllocator& _alloc)
    : model_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _model_name_type;
  _model_name_type model_name;





  typedef boost::shared_ptr< ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GazeboDeleteModelRequest_

typedef ::mrs_msgs::GazeboDeleteModelRequest_<std::allocator<void> > GazeboDeleteModelRequest;

typedef boost::shared_ptr< ::mrs_msgs::GazeboDeleteModelRequest > GazeboDeleteModelRequestPtr;
typedef boost::shared_ptr< ::mrs_msgs::GazeboDeleteModelRequest const> GazeboDeleteModelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator1> & lhs, const ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator2> & rhs)
{
  return lhs.model_name == rhs.model_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator1> & lhs, const ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea31c8eab6fc401383cf528a7c0984ba";
  }

  static const char* value(const ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea31c8eab6fc4013ULL;
  static const uint64_t static_value2 = 0x83cf528a7c0984baULL;
};

template<class ContainerAllocator>
struct DataType< ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrs_msgs/GazeboDeleteModelRequest";
  }

  static const char* value(const ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A service to delete a model in a Gazebo simulation\n"
"# using the mrs_gazebo_ros_interface package.\n"
"\n"
"# Name of the model to be deleted.\n"
"string model_name\n"
"\n"
;
  }

  static const char* value(const ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GazeboDeleteModelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrs_msgs::GazeboDeleteModelRequest_<ContainerAllocator>& v)
  {
    s << indent << "model_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.model_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRS_MSGS_MESSAGE_GAZEBODELETEMODELREQUEST_H
