// Generated by gencpp from file mrs_msgs/GazeboAttachTypedRequest.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_GAZEBOATTACHTYPEDREQUEST_H
#define MRS_MSGS_MESSAGE_GAZEBOATTACHTYPEDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrs_msgs
{
template <class ContainerAllocator>
struct GazeboAttachTypedRequest_
{
  typedef GazeboAttachTypedRequest_<ContainerAllocator> Type;

  GazeboAttachTypedRequest_()
    : model_name_1()
    , link_name_1()
    , model_name_2()
    , link_name_2()
    , joint_type()  {
    }
  GazeboAttachTypedRequest_(const ContainerAllocator& _alloc)
    : model_name_1(_alloc)
    , link_name_1(_alloc)
    , model_name_2(_alloc)
    , link_name_2(_alloc)
    , joint_type(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _model_name_1_type;
  _model_name_1_type model_name_1;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _link_name_1_type;
  _link_name_1_type link_name_1;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _model_name_2_type;
  _model_name_2_type model_name_2;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _link_name_2_type;
  _link_name_2_type link_name_2;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _joint_type_type;
  _joint_type_type joint_type;





  typedef boost::shared_ptr< ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GazeboAttachTypedRequest_

typedef ::mrs_msgs::GazeboAttachTypedRequest_<std::allocator<void> > GazeboAttachTypedRequest;

typedef boost::shared_ptr< ::mrs_msgs::GazeboAttachTypedRequest > GazeboAttachTypedRequestPtr;
typedef boost::shared_ptr< ::mrs_msgs::GazeboAttachTypedRequest const> GazeboAttachTypedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator1> & lhs, const ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator2> & rhs)
{
  return lhs.model_name_1 == rhs.model_name_1 &&
    lhs.link_name_1 == rhs.link_name_1 &&
    lhs.model_name_2 == rhs.model_name_2 &&
    lhs.link_name_2 == rhs.link_name_2 &&
    lhs.joint_type == rhs.joint_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator1> & lhs, const ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f71ab065e7816263cf291f9ab0527af";
  }

  static const char* value(const ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f71ab065e781626ULL;
  static const uint64_t static_value2 = 0x3cf291f9ab0527afULL;
};

template<class ContainerAllocator>
struct DataType< ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrs_msgs/GazeboAttachTypedRequest";
  }

  static const char* value(const ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A service to apply a force and/or torque to a link in a Gazebo simulation\n"
"# using the mrs_gazebo_ros_interface package.\n"
"\n"
"# Name of the model, containing the first link to be joined.\n"
"string model_name_1\n"
"\n"
"# Name the first link to be joined.\n"
"string link_name_1\n"
"\n"
"# Name of the model, containing the second link to be joined.\n"
"string model_name_2\n"
"\n"
"# Name of the second link to be joined.\n"
"string link_name_2\n"
"\n"
"# Type of the joint to be created.\n"
"# This should be one of the following values:\n"
"# \"revolute\"\n"
"# \"ball\"\n"
"# \"gearbox\"\n"
"# \"prismatic\"\n"
"# \"revolute2\"\n"
"# \"universal\"\n"
"# \"piston\"\n"
"# \"fixed\"\n"
"string joint_type\n"
"\n"
;
  }

  static const char* value(const ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model_name_1);
      stream.next(m.link_name_1);
      stream.next(m.model_name_2);
      stream.next(m.link_name_2);
      stream.next(m.joint_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GazeboAttachTypedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrs_msgs::GazeboAttachTypedRequest_<ContainerAllocator>& v)
  {
    s << indent << "model_name_1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.model_name_1);
    s << indent << "link_name_1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.link_name_1);
    s << indent << "model_name_2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.model_name_2);
    s << indent << "link_name_2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.link_name_2);
    s << indent << "joint_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.joint_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRS_MSGS_MESSAGE_GAZEBOATTACHTYPEDREQUEST_H
