// Generated by gencpp from file mrs_msgs/GpsData.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_GPSDATA_H
#define MRS_MSGS_MESSAGE_GPSDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrs_msgs
{
template <class ContainerAllocator>
struct GpsData_
{
  typedef GpsData_<ContainerAllocator> Type;

  GpsData_()
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , covariance()  {
      covariance.assign(0.0);
  }
  GpsData_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , covariance()  {
  (void)_alloc;
      covariance.assign(0.0);
  }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef boost::array<double, 9>  _covariance_type;
  _covariance_type covariance;





  typedef boost::shared_ptr< ::mrs_msgs::GpsData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrs_msgs::GpsData_<ContainerAllocator> const> ConstPtr;

}; // struct GpsData_

typedef ::mrs_msgs::GpsData_<std::allocator<void> > GpsData;

typedef boost::shared_ptr< ::mrs_msgs::GpsData > GpsDataPtr;
typedef boost::shared_ptr< ::mrs_msgs::GpsData const> GpsDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrs_msgs::GpsData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrs_msgs::GpsData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrs_msgs::GpsData_<ContainerAllocator1> & lhs, const ::mrs_msgs::GpsData_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude &&
    lhs.covariance == rhs.covariance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrs_msgs::GpsData_<ContainerAllocator1> & lhs, const ::mrs_msgs::GpsData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::GpsData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::GpsData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::GpsData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::GpsData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::GpsData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::GpsData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrs_msgs::GpsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11a1c53709b7798891fc9160dc190160";
  }

  static const char* value(const ::mrs_msgs::GpsData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11a1c53709b77988ULL;
  static const uint64_t static_value2 = 0x91fc9160dc190160ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrs_msgs::GpsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrs_msgs/GpsData";
  }

  static const char* value(const ::mrs_msgs::GpsData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrs_msgs::GpsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n"
"float64 longitude\n"
"float64 altitude\n"
"float64[9] covariance\n"
;
  }

  static const char* value(const ::mrs_msgs::GpsData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrs_msgs::GpsData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.covariance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrs_msgs::GpsData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrs_msgs::GpsData_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "covariance[]" << std::endl;
    for (size_t i = 0; i < v.covariance.size(); ++i)
    {
      s << indent << "  covariance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.covariance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRS_MSGS_MESSAGE_GPSDATA_H
