// Generated by gencpp from file mrs_msgs/Int32MultiArrayStamped.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_INT32MULTIARRAYSTAMPED_H
#define MRS_MSGS_MESSAGE_INT32MULTIARRAYSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/MultiArrayLayout.h>

namespace mrs_msgs
{
template <class ContainerAllocator>
struct Int32MultiArrayStamped_
{
  typedef Int32MultiArrayStamped_<ContainerAllocator> Type;

  Int32MultiArrayStamped_()
    : stamp()
    , layout()
    , data()  {
    }
  Int32MultiArrayStamped_(const ContainerAllocator& _alloc)
    : stamp()
    , layout(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef  ::std_msgs::MultiArrayLayout_<ContainerAllocator>  _layout_type;
  _layout_type layout;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> const> ConstPtr;

}; // struct Int32MultiArrayStamped_

typedef ::mrs_msgs::Int32MultiArrayStamped_<std::allocator<void> > Int32MultiArrayStamped;

typedef boost::shared_ptr< ::mrs_msgs::Int32MultiArrayStamped > Int32MultiArrayStampedPtr;
typedef boost::shared_ptr< ::mrs_msgs::Int32MultiArrayStamped const> Int32MultiArrayStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator1> & lhs, const ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.layout == rhs.layout &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator1> & lhs, const ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5990e7873345bc503fec41948a48ffa4";
  }

  static const char* value(const ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5990e7873345bc50ULL;
  static const uint64_t static_value2 = 0x3fec41948a48ffa4ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrs_msgs/Int32MultiArrayStamped";
  }

  static const char* value(const ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"std_msgs/MultiArrayLayout layout\n"
"int32[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.layout);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Int32MultiArrayStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrs_msgs::Int32MultiArrayStamped_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "layout: ";
    s << std::endl;
    Printer< ::std_msgs::MultiArrayLayout_<ContainerAllocator> >::stream(s, indent + "  ", v.layout);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRS_MSGS_MESSAGE_INT32MULTIARRAYSTAMPED_H
