// Generated by gencpp from file mrs_msgs/PathSrv.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_PATHSRV_H
#define MRS_MSGS_MESSAGE_PATHSRV_H

#include <ros/service_traits.h>


#include <mrs_msgs/PathSrvRequest.h>
#include <mrs_msgs/PathSrvResponse.h>


namespace mrs_msgs
{

struct PathSrv
{

typedef PathSrvRequest Request;
typedef PathSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PathSrv
} // namespace mrs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mrs_msgs::PathSrv > {
  static const char* value()
  {
    return "cc0419be56f5b03e64c4b130ea5ebe7f";
  }

  static const char* value(const ::mrs_msgs::PathSrv&) { return value(); }
};

template<>
struct DataType< ::mrs_msgs::PathSrv > {
  static const char* value()
  {
    return "mrs_msgs/PathSrv";
  }

  static const char* value(const ::mrs_msgs::PathSrv&) { return value(); }
};


// service_traits::MD5Sum< ::mrs_msgs::PathSrvRequest> should match
// service_traits::MD5Sum< ::mrs_msgs::PathSrv >
template<>
struct MD5Sum< ::mrs_msgs::PathSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mrs_msgs::PathSrv >::value();
  }
  static const char* value(const ::mrs_msgs::PathSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrs_msgs::PathSrvRequest> should match
// service_traits::DataType< ::mrs_msgs::PathSrv >
template<>
struct DataType< ::mrs_msgs::PathSrvRequest>
{
  static const char* value()
  {
    return DataType< ::mrs_msgs::PathSrv >::value();
  }
  static const char* value(const ::mrs_msgs::PathSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mrs_msgs::PathSrvResponse> should match
// service_traits::MD5Sum< ::mrs_msgs::PathSrv >
template<>
struct MD5Sum< ::mrs_msgs::PathSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mrs_msgs::PathSrv >::value();
  }
  static const char* value(const ::mrs_msgs::PathSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrs_msgs::PathSrvResponse> should match
// service_traits::DataType< ::mrs_msgs::PathSrv >
template<>
struct DataType< ::mrs_msgs::PathSrvResponse>
{
  static const char* value()
  {
    return DataType< ::mrs_msgs::PathSrv >::value();
  }
  static const char* value(const ::mrs_msgs::PathSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MRS_MSGS_MESSAGE_PATHSRV_H
