// Generated by gencpp from file mrs_msgs/Point2DWithFloat.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_POINT2DWITHFLOAT_H
#define MRS_MSGS_MESSAGE_POINT2DWITHFLOAT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrs_msgs
{
template <class ContainerAllocator>
struct Point2DWithFloat_
{
  typedef Point2DWithFloat_<ContainerAllocator> Type;

  Point2DWithFloat_()
    : x(0.0)
    , y(0.0)
    , value(0.0)  {
    }
  Point2DWithFloat_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> const> ConstPtr;

}; // struct Point2DWithFloat_

typedef ::mrs_msgs::Point2DWithFloat_<std::allocator<void> > Point2DWithFloat;

typedef boost::shared_ptr< ::mrs_msgs::Point2DWithFloat > Point2DWithFloatPtr;
typedef boost::shared_ptr< ::mrs_msgs::Point2DWithFloat const> Point2DWithFloatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrs_msgs::Point2DWithFloat_<ContainerAllocator1> & lhs, const ::mrs_msgs::Point2DWithFloat_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrs_msgs::Point2DWithFloat_<ContainerAllocator1> & lhs, const ::mrs_msgs::Point2DWithFloat_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0746f45a08a06584bdbb3bc2f191f38";
  }

  static const char* value(const ::mrs_msgs::Point2DWithFloat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0746f45a08a0658ULL;
  static const uint64_t static_value2 = 0x4bdbb3bc2f191f38ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrs_msgs/Point2DWithFloat";
  }

  static const char* value(const ::mrs_msgs::Point2DWithFloat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 value\n"
;
  }

  static const char* value(const ::mrs_msgs::Point2DWithFloat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point2DWithFloat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrs_msgs::Point2DWithFloat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrs_msgs::Point2DWithFloat_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRS_MSGS_MESSAGE_POINT2DWITHFLOAT_H
