// Generated by gencpp from file mrs_msgs/PoseWithCovarianceIdentified.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_POSEWITHCOVARIANCEIDENTIFIED_H
#define MRS_MSGS_MESSAGE_POSEWITHCOVARIANCEIDENTIFIED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace mrs_msgs
{
template <class ContainerAllocator>
struct PoseWithCovarianceIdentified_
{
  typedef PoseWithCovarianceIdentified_<ContainerAllocator> Type;

  PoseWithCovarianceIdentified_()
    : id(0)
    , pose()
    , covariance()  {
      covariance.assign(0.0);
  }
  PoseWithCovarianceIdentified_(const ContainerAllocator& _alloc)
    : id(0)
    , pose(_alloc)
    , covariance()  {
  (void)_alloc;
      covariance.assign(0.0);
  }



   typedef uint64_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef boost::array<double, 36>  _covariance_type;
  _covariance_type covariance;





  typedef boost::shared_ptr< ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> const> ConstPtr;

}; // struct PoseWithCovarianceIdentified_

typedef ::mrs_msgs::PoseWithCovarianceIdentified_<std::allocator<void> > PoseWithCovarianceIdentified;

typedef boost::shared_ptr< ::mrs_msgs::PoseWithCovarianceIdentified > PoseWithCovarianceIdentifiedPtr;
typedef boost::shared_ptr< ::mrs_msgs::PoseWithCovarianceIdentified const> PoseWithCovarianceIdentifiedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator1> & lhs, const ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pose == rhs.pose &&
    lhs.covariance == rhs.covariance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator1> & lhs, const ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcebff621732fb590dbf67c491184e03";
  }

  static const char* value(const ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdcebff621732fb59ULL;
  static const uint64_t static_value2 = 0x0dbf67c491184e03ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrs_msgs/PoseWithCovarianceIdentified";
  }

  static const char* value(const ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 id\n"
"geometry_msgs/Pose pose\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pose);
      stream.next(m.covariance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseWithCovarianceIdentified_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrs_msgs::PoseWithCovarianceIdentified_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "covariance[]" << std::endl;
    for (size_t i = 0; i < v.covariance.size(); ++i)
    {
      s << indent << "  covariance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.covariance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRS_MSGS_MESSAGE_POSEWITHCOVARIANCEIDENTIFIED_H
