// Generated by gencpp from file mrs_msgs/RadarData.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_RADARDATA_H
#define MRS_MSGS_MESSAGE_RADARDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mrs_msgs
{
template <class ContainerAllocator>
struct RadarData_
{
  typedef RadarData_<ContainerAllocator> Type;

  RadarData_()
    : header()
    , direction(false)
    , velocity(0.0)
    , counter(0)  {
    }
  RadarData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , direction(false)
    , velocity(0.0)
    , counter(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _direction_type;
  _direction_type direction;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef int32_t _counter_type;
  _counter_type counter;





  typedef boost::shared_ptr< ::mrs_msgs::RadarData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrs_msgs::RadarData_<ContainerAllocator> const> ConstPtr;

}; // struct RadarData_

typedef ::mrs_msgs::RadarData_<std::allocator<void> > RadarData;

typedef boost::shared_ptr< ::mrs_msgs::RadarData > RadarDataPtr;
typedef boost::shared_ptr< ::mrs_msgs::RadarData const> RadarDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrs_msgs::RadarData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrs_msgs::RadarData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrs_msgs::RadarData_<ContainerAllocator1> & lhs, const ::mrs_msgs::RadarData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.direction == rhs.direction &&
    lhs.velocity == rhs.velocity &&
    lhs.counter == rhs.counter;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrs_msgs::RadarData_<ContainerAllocator1> & lhs, const ::mrs_msgs::RadarData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::RadarData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::RadarData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::RadarData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::RadarData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::RadarData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::RadarData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrs_msgs::RadarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b201a3c91369a1dcb1372493c6e8ca4d";
  }

  static const char* value(const ::mrs_msgs::RadarData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb201a3c91369a1dcULL;
  static const uint64_t static_value2 = 0xb1372493c6e8ca4dULL;
};

template<class ContainerAllocator>
struct DataType< ::mrs_msgs::RadarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrs_msgs/RadarData";
  }

  static const char* value(const ::mrs_msgs::RadarData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrs_msgs::RadarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool direction\n"
"float32 velocity\n"
"int32 counter\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mrs_msgs::RadarData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrs_msgs::RadarData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.direction);
      stream.next(m.velocity);
      stream.next(m.counter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrs_msgs::RadarData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrs_msgs::RadarData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direction);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "counter: ";
    Printer<int32_t>::stream(s, indent + "  ", v.counter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRS_MSGS_MESSAGE_RADARDATA_H
