// Generated by gencpp from file mrs_msgs/TransformVector3Srv.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_TRANSFORMVECTOR3SRV_H
#define MRS_MSGS_MESSAGE_TRANSFORMVECTOR3SRV_H

#include <ros/service_traits.h>


#include <mrs_msgs/TransformVector3SrvRequest.h>
#include <mrs_msgs/TransformVector3SrvResponse.h>


namespace mrs_msgs
{

struct TransformVector3Srv
{

typedef TransformVector3SrvRequest Request;
typedef TransformVector3SrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TransformVector3Srv
} // namespace mrs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mrs_msgs::TransformVector3Srv > {
  static const char* value()
  {
    return "997fb77f6976e071a4e765fdba14bb92";
  }

  static const char* value(const ::mrs_msgs::TransformVector3Srv&) { return value(); }
};

template<>
struct DataType< ::mrs_msgs::TransformVector3Srv > {
  static const char* value()
  {
    return "mrs_msgs/TransformVector3Srv";
  }

  static const char* value(const ::mrs_msgs::TransformVector3Srv&) { return value(); }
};


// service_traits::MD5Sum< ::mrs_msgs::TransformVector3SrvRequest> should match
// service_traits::MD5Sum< ::mrs_msgs::TransformVector3Srv >
template<>
struct MD5Sum< ::mrs_msgs::TransformVector3SrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mrs_msgs::TransformVector3Srv >::value();
  }
  static const char* value(const ::mrs_msgs::TransformVector3SrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrs_msgs::TransformVector3SrvRequest> should match
// service_traits::DataType< ::mrs_msgs::TransformVector3Srv >
template<>
struct DataType< ::mrs_msgs::TransformVector3SrvRequest>
{
  static const char* value()
  {
    return DataType< ::mrs_msgs::TransformVector3Srv >::value();
  }
  static const char* value(const ::mrs_msgs::TransformVector3SrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mrs_msgs::TransformVector3SrvResponse> should match
// service_traits::MD5Sum< ::mrs_msgs::TransformVector3Srv >
template<>
struct MD5Sum< ::mrs_msgs::TransformVector3SrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mrs_msgs::TransformVector3Srv >::value();
  }
  static const char* value(const ::mrs_msgs::TransformVector3SrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrs_msgs::TransformVector3SrvResponse> should match
// service_traits::DataType< ::mrs_msgs::TransformVector3Srv >
template<>
struct DataType< ::mrs_msgs::TransformVector3SrvResponse>
{
  static const char* value()
  {
    return DataType< ::mrs_msgs::TransformVector3Srv >::value();
  }
  static const char* value(const ::mrs_msgs::TransformVector3SrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MRS_MSGS_MESSAGE_TRANSFORMVECTOR3SRV_H
