// Generated by gencpp from file mrs_msgs/ValidateReferenceListRequest.msg
// DO NOT EDIT!


#ifndef MRS_MSGS_MESSAGE_VALIDATEREFERENCELISTREQUEST_H
#define MRS_MSGS_MESSAGE_VALIDATEREFERENCELISTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mrs_msgs/ReferenceList.h>

namespace mrs_msgs
{
template <class ContainerAllocator>
struct ValidateReferenceListRequest_
{
  typedef ValidateReferenceListRequest_<ContainerAllocator> Type;

  ValidateReferenceListRequest_()
    : list()  {
    }
  ValidateReferenceListRequest_(const ContainerAllocator& _alloc)
    : list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mrs_msgs::ReferenceList_<ContainerAllocator>  _list_type;
  _list_type list;





  typedef boost::shared_ptr< ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ValidateReferenceListRequest_

typedef ::mrs_msgs::ValidateReferenceListRequest_<std::allocator<void> > ValidateReferenceListRequest;

typedef boost::shared_ptr< ::mrs_msgs::ValidateReferenceListRequest > ValidateReferenceListRequestPtr;
typedef boost::shared_ptr< ::mrs_msgs::ValidateReferenceListRequest const> ValidateReferenceListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator1> & lhs, const ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator2> & rhs)
{
  return lhs.list == rhs.list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator1> & lhs, const ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1970fbb134b0c597ae73fed14084253";
  }

  static const char* value(const ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1970fbb134b0c59ULL;
  static const uint64_t static_value2 = 0x7ae73fed14084253ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrs_msgs/ValidateReferenceListRequest";
  }

  static const char* value(const ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrs_msgs/ReferenceList list\n"
"\n"
"================================================================================\n"
"MSG: mrs_msgs/ReferenceList\n"
"# A list of references.\n"
"\n"
"std_msgs/Header header\n"
"mrs_msgs/Reference[] list\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mrs_msgs/Reference\n"
"# This message defines a control reference with a Position+Heading.\n"
"\n"
"geometry_msgs/Point position\n"
"\n"
"# Heading is atan2() of XY-world projection of the UAV's body X-axis.\n"
"float64 heading\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ValidateReferenceListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrs_msgs::ValidateReferenceListRequest_<ContainerAllocator>& v)
  {
    s << indent << "list: ";
    s << std::endl;
    Printer< ::mrs_msgs::ReferenceList_<ContainerAllocator> >::stream(s, indent + "  ", v.list);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRS_MSGS_MESSAGE_VALIDATEREFERENCELISTREQUEST_H
