(cl:in-package mrs_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MESSAGE_ID-VAL
          MESSAGE_ID
          UTC_SECONDS-VAL
          UTC_SECONDS
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE_DIR-VAL
          LATITUDE_DIR
          LONGITUDE_DIR-VAL
          LONGITUDE_DIR
          GPS_QUALITY-VAL
          GPS_QUALITY
          NUM_SATS-VAL
          NUM_SATS
          HDOP-VAL
          HDOP
          ALTITUDE-VAL
          ALTITUDE
          ALTITUDE_UNITS-VAL
          ALTITUDE_UNITS
          UNDULATION-VAL
          UNDULATION
          UNDULATION_UNITS-VAL
          UNDULATION_UNITS
          DIFF_AGE-VAL
          DIFF_AGE
          STATION_ID-VAL
          STATION_ID
))