(cl:in-package mrs_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MAX_ALTITUDE-VAL
          MAX_ALTITUDE
          ESTIMATOR_TYPE-VAL
          ESTIMATOR_TYPE
          HEADING_TYPE-VAL
          HEADING_TYPE
          ALTITUDE_TYPE-VAL
          ALTITUDE_TYPE
          AVAILABLE_LAT_ESTIMATORS-VAL
          AVAILABLE_LAT_ESTIMATORS
          AVAILABLE_HDG_ESTIMATORS-VAL
          AVAILABLE_HDG_ESTIMATORS
          AVAILABLE_ALT_ESTIMATORS-VAL
          AVAILABLE_ALT_ESTIMATORS
))