(cl:in-package mrs_msgs-msg)
(cl:export '(STAMP-VAL
          STAMP
          UAV_NAME-VAL
          UAV_NAME
          MOTORS-VAL
          MOTORS
          FLYING_NORMALLY-VAL
          FLYING_NORMALLY
          RC_MODE-VAL
          RC_MODE
          ACTIVE_TRACKER-VAL
          ACTIVE_TRACKER
          TRACKER_STATUS-VAL
          TRACKER_STATUS
          ACTIVE_CONTROLLER-VAL
          ACTIVE_CONTROLLER
          CONTROLLER_STATUS-VAL
          CONTROLLER_STATUS
          AVAILABLE_CONTROLLERS-VAL
          AVAILABLE_CONTROLLERS
          AVAILABLE_TRACKERS-VAL
          AVAILABLE_TRACKERS
          HUMAN_SWITCHABLE_CONTROLLERS-VAL
          HUMAN_SWITCHABLE_CONTROLLERS
          HUMAN_SWITCHABLE_TRACKERS-VAL
          HUMAN_SWITCHABLE_TRACKERS
))