(cl:in-package mrs_msgs-msg)
(cl:export '(STAMP-VAL
          STAMP
          MES_VBAT-VAL
          MES_VBAT
          MES_24V-VAL
          MES_24V
          MES_VARM-VAL
          MES_VARM
          MES_19V-VAL
          MES_19V
          MES_5V-VAL
          MES_5V
          PWM_ENABLED-VAL
          PWM_ENABLED
          PWM1_VAL-VAL
          PWM1_VAL
          PWM2_VAL-VAL
          PWM2_VAL
          PWM3_VAL-VAL
          PWM3_VAL
          PWM4_VAL-VAL
          PWM4_VAL
          PWM5_VAL-VAL
          PWM5_VAL
          PWM6_VAL-VAL
          PWM6_VAL
          SOLENOIDS_ARMED-VAL
          SOLENOIDS_ARMED
          LAUNCHED_CH1-VAL
          LAUNCHED_CH1
          LAUNCHED_CH2-VAL
          LAUNCHED_CH2
          LAUNCHED_CH3-VAL
          LAUNCHED_CH3
          LAUNCHED_CH4-VAL
          LAUNCHED_CH4
          LAUNCHED_CH5-VAL
          LAUNCHED_CH5
          LAUNCHED_CH6-VAL
          LAUNCHED_CH6
))