(cl:in-package mrs_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DURATION_ALL-VAL
          DURATION_ALL
          DURATION_ALOAM-VAL
          DURATION_ALOAM
          DURATION_GARMIN-VAL
          DURATION_GARMIN
          DURATION_BARO-VAL
          DURATION_BARO
          DURATION_INPUT-VAL
          DURATION_INPUT
          DURATION_REST-VAL
          DURATION_REST
          TIMESTAMP_DIFF_ALL-VAL
          TIMESTAMP_DIFF_ALL
          TIMESTAMP_DIFF_ALOAM-VAL
          TIMESTAMP_DIFF_ALOAM
          TIMESTAMP_DIFF_GARMIN-VAL
          TIMESTAMP_DIFF_GARMIN
          TIMESTAMP_DIFF_BARO-VAL
          TIMESTAMP_DIFF_BARO
          TIMESTAMP_DIFF_INPUT-VAL
          TIMESTAMP_DIFF_INPUT
          TIMESTAMP_DIFF_REST-VAL
          TIMESTAMP_DIFF_REST
))