(cl:in-package mrs_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          UAV_NAME-VAL
          UAV_NAME
          NATO_NAME-VAL
          NATO_NAME
          UAV_TYPE-VAL
          UAV_TYPE
          UAV_MASS-VAL
          UAV_MASS
          CONTROL_MANAGER_DIAG_HZ-VAL
          CONTROL_MANAGER_DIAG_HZ
          CONTROL_MANAGER_DIAG_COLOR-VAL
          CONTROL_MANAGER_DIAG_COLOR
          CONTROLLERS-VAL
          CONTROLLERS
          GAINS-VAL
          GAINS
          TRACKERS-VAL
          TRACKERS
          CONSTRAINTS-VAL
          CONSTRAINTS
          FLY_STATE-VAL
          FLY_STATE
          NULL_TRACKER-VAL
          NULL_TRACKER
          SECS_FLOWN-VAL
          SECS_FLOWN
          ODOM_HZ-VAL
          ODOM_HZ
          ODOM_COLOR-VAL
          ODOM_COLOR
          ODOM_X-VAL
          ODOM_X
          ODOM_Y-VAL
          ODOM_Y
          ODOM_Z-VAL
          ODOM_Z
          ODOM_HDG-VAL
          ODOM_HDG
          ODOM_FRAME-VAL
          ODOM_FRAME
          ODOM_ESTIMATORS_HORI-VAL
          ODOM_ESTIMATORS_HORI
          ODOM_ESTIMATORS_VERT-VAL
          ODOM_ESTIMATORS_VERT
          ODOM_ESTIMATORS_HDG-VAL
          ODOM_ESTIMATORS_HDG
          CMD_X-VAL
          CMD_X
          CMD_Y-VAL
          CMD_Y
          CMD_Z-VAL
          CMD_Z
          CMD_HDG-VAL
          CMD_HDG
          CPU_LOAD-VAL
          CPU_LOAD
          CPU_LOAD_TOTAL-VAL
          CPU_LOAD_TOTAL
          CPU_GHZ-VAL
          CPU_GHZ
          CPU_TEMPERATURE-VAL
          CPU_TEMPERATURE
          FREE_RAM-VAL
          FREE_RAM
          TOTAL_RAM-VAL
          TOTAL_RAM
          FREE_HDD-VAL
          FREE_HDD
          MAVROS_HZ-VAL
          MAVROS_HZ
          MAVROS_COLOR-VAL
          MAVROS_COLOR
          MAVROS_BATTERY_HZ-VAL
          MAVROS_BATTERY_HZ
          MAVROS_STATE_HZ-VAL
          MAVROS_STATE_HZ
          MAVROS_CMD_HZ-VAL
          MAVROS_CMD_HZ
          MAVROS_MODE-VAL
          MAVROS_MODE
          MAVROS_ARMED-VAL
          MAVROS_ARMED
          MAVROS_GPS_OK-VAL
          MAVROS_GPS_OK
          MAVROS_GPS_QUAL-VAL
          MAVROS_GPS_QUAL
          BATTERY_VOLT-VAL
          BATTERY_VOLT
          BATTERY_CURR-VAL
          BATTERY_CURR
          BATTERY_WH_DRAINED-VAL
          BATTERY_WH_DRAINED
          THRUST-VAL
          THRUST
          MASS_ESTIMATE-VAL
          MASS_ESTIMATE
          MASS_SET-VAL
          MASS_SET
          CUSTOM_TOPICS-VAL
          CUSTOM_TOPICS
          CUSTOM_STRING_OUTPUTS-VAL
          CUSTOM_STRING_OUTPUTS
          CUSTOM_SERVICES-VAL
          CUSTOM_SERVICES
          NODE_CPU_LOADS-VAL
          NODE_CPU_LOADS
          FLYING_NORMALLY-VAL
          FLYING_NORMALLY
          HAVE_GOAL-VAL
          HAVE_GOAL
          CALLBACKS_ENABLED-VAL
          CALLBACKS_ENABLED
          COLLISION_AVOIDANCE_ENABLED-VAL
          COLLISION_AVOIDANCE_ENABLED
          AVOIDING_COLLISION-VAL
          AVOIDING_COLLISION
          AUTOMATIC_START_CAN_TAKEOFF-VAL
          AUTOMATIC_START_CAN_TAKEOFF
          NUM_OTHER_UAVS-VAL
          NUM_OTHER_UAVS
))