(cl:in-package mrs_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          INPUT_ID-VAL
          INPUT_ID
          USE_HEADING-VAL
          USE_HEADING
          FLY_NOW-VAL
          FLY_NOW
          STOP_AT_WAYPOINTS-VAL
          STOP_AT_WAYPOINTS
          LOOP-VAL
          LOOP
          OVERRIDE_CONSTRAINTS-VAL
          OVERRIDE_CONSTRAINTS
          OVERRIDE_MAX_VELOCITY_HORIZONTAL-VAL
          OVERRIDE_MAX_VELOCITY_HORIZONTAL
          OVERRIDE_MAX_ACCELERATION_HORIZONTAL-VAL
          OVERRIDE_MAX_ACCELERATION_HORIZONTAL
          OVERRIDE_MAX_VELOCITY_VERTICAL-VAL
          OVERRIDE_MAX_VELOCITY_VERTICAL
          OVERRIDE_MAX_ACCELERATION_VERTICAL-VAL
          OVERRIDE_MAX_ACCELERATION_VERTICAL
          RELAX_HEADING-VAL
          RELAX_HEADING
          POINTS-VAL
          POINTS
))