(cl:in-package mrs_msgs-msg)
(cl:export '(KPXY-VAL
          KPXY
          KVXY-VAL
          KVXY
          KAXY-VAL
          KAXY
          KPZ-VAL
          KPZ
          KVZ-VAL
          KVZ
          KAZ-VAL
          KAZ
          KQXY-VAL
          KQXY
          KIBXY-VAL
          KIBXY
          KIBXY_LIM-VAL
          KIBXY_LIM
          KIWXY-VAL
          KIWXY
          KIWXY_LIM-VAL
          KIWXY_LIM
          KQZ-VAL
          KQZ
          KM-VAL
          KM
          KM_LIM-VAL
          KM_LIM
))