(cl:in-package mrs_msgs-msg)
(cl:export '(NAME-VAL
          NAME
          SN-VAL
          SN
          FW_REV-VAL
          FW_REV
          MODE-VAL
          MODE
          PROD_LINE-VAL
          PROD_LINE
          BEAM_AZIMUTH_ANGLES-VAL
          BEAM_AZIMUTH_ANGLES
          BEAM_ALTITUDE_ANGLES-VAL
          BEAM_ALTITUDE_ANGLES
          LIDAR_ORIGIN_TO_BEAM_ORIGIN_MM-VAL
          LIDAR_ORIGIN_TO_BEAM_ORIGIN_MM
          IMU_TO_SENSOR_TRANSFORM-VAL
          IMU_TO_SENSOR_TRANSFORM
          LIDAR_TO_SENSOR_TRANSFORM-VAL
          LIDAR_TO_SENSOR_TRANSFORM
          EXTRINSIC-VAL
          EXTRINSIC
          PIXELS_PER_COLUMN-VAL
          PIXELS_PER_COLUMN
          COLUMNS_PER_FRAME-VAL
          COLUMNS_PER_FRAME
          PIXEL_SHIFT_BY_ROW-VAL
          PIXEL_SHIFT_BY_ROW
))