# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mrs_msgs/LandoffDiagnostics.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class LandoffDiagnostics(genpy.Message):
  _md5sum = "1feb5898812832580fccb73c0f05b11a"
  _type = "mrs_msgs/LandoffDiagnostics"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
bool active
bool landing
bool taking_off
bool elanding
"""
  __slots__ = ['stamp','active','landing','taking_off','elanding']
  _slot_types = ['time','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,active,landing,taking_off,elanding

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LandoffDiagnostics, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.active is None:
        self.active = False
      if self.landing is None:
        self.landing = False
      if self.taking_off is None:
        self.taking_off = False
      if self.elanding is None:
        self.elanding = False
    else:
      self.stamp = genpy.Time()
      self.active = False
      self.landing = False
      self.taking_off = False
      self.elanding = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I4B().pack(_x.stamp.secs, _x.stamp.nsecs, _x.active, _x.landing, _x.taking_off, _x.elanding))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.stamp.secs, _x.stamp.nsecs, _x.active, _x.landing, _x.taking_off, _x.elanding,) = _get_struct_2I4B().unpack(str[start:end])
      self.active = bool(self.active)
      self.landing = bool(self.landing)
      self.taking_off = bool(self.taking_off)
      self.elanding = bool(self.elanding)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I4B().pack(_x.stamp.secs, _x.stamp.nsecs, _x.active, _x.landing, _x.taking_off, _x.elanding))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.stamp.secs, _x.stamp.nsecs, _x.active, _x.landing, _x.taking_off, _x.elanding,) = _get_struct_2I4B().unpack(str[start:end])
      self.active = bool(self.active)
      self.landing = bool(self.landing)
      self.taking_off = bool(self.taking_off)
      self.elanding = bool(self.elanding)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I4B = None
def _get_struct_2I4B():
    global _struct_2I4B
    if _struct_2I4B is None:
        _struct_2I4B = struct.Struct("<2I4B")
    return _struct_2I4B
