
planning_tree:
  resolution: 0.4

distance_transform:
  submap_distance: 20.0 # [m] from the UAV into all directions

main_timer:
  rate: 20.0 # [Hz]

diagnostics_timer:
  rate: 10.0 # [Hz]

future_check_timer:
  rate: 10.0 # [Hz]

euclidean_distance_cutoff: 1.0 # [m]
safe_obstacle_distance: 1.0 # [m]

min_path_length: 0.2 # [m]

distance_penalty: 1.0
greedy_penalty: 1.0

max_waypoint_distance: 0.0 # [m] // or set negative for no padding
min_altitude: -1000.0 # [m]
max_altitude: 1000.0 # [m]
unknown_is_occupied: true
replan_after: 1.0 # [s]

timeout_threshold: 2.0 # [s]
time_for_trajectory_generator: 0.1 # [s]

trajectory_generator:
  input_trajectory_length: 12.0 # [s] (the rest of path will be ignored during trajectory generation)
  relax_heading: false # if true, constraints on heading dynamics are ignored during trajectory generation process
  use_heading: true # if false heading is ignored during trajectory tracking
  heading_offset: 0.0 # [rad] offset of desired heading to direction of flight 
  turn_in_flight_direction: true # sample heading reference in direction of flight 
  max_segment_length_heading: 1.0 # [m] maximum length of segment for heading sampling

subt_planner: 
  use: true
  apply_postprocessing: true
  make_path_straight: false # cannot be applied if postprocessing is active
  debug_info: false
  clearing_dist: 0.15 # [m] clear occupied and unknown space up to this distance from the starting position, might cause collision if greater than min_path_length
  admissibility: 1.0 # allows paths of length up to (admissibility * optimum length)

  apply_pruning: true
  pruning_dist: 0.6
  
  planning_tree: 
    bounding_box: 
      horizontal: 60.0 # (m)
      vertical: 30.0 # (m)

  postprocessing: 
    safe_dist: 2.5 # (m)
    max_iteration: 5
    horizontal_neighbors_only: true
    z_diff_tolerance: 0.5 # (m)
    fix_goal_point: true

  shortening: 
    window_size: 20
    distance: 1.0 # (m)

# visualization
points_scale: 0.05
lines_scale: 0.02
