(cl:in-package mrs_msgs-srv)
(cl:export '(HORIZONTAL_LIMIT-VAL
          HORIZONTAL_LIMIT
          VERTICAL_LIMIT-VAL
          VERTICAL_LIMIT
          REPULSION_HORIZONTAL_LIMIT-VAL
          REPULSION_HORIZONTAL_LIMIT
          REPULSION_VERTICAL_LIMIT-VAL
          REPULSION_VERTICAL_LIMIT
          REPULSION_HORIZONTAL_OFFSET-VAL
          REPULSION_HORIZONTAL_OFFSET
          REPULSION_VERTICAL_OFFSET-VAL
          REPULSION_VERTICAL_OFFSET
          SUCCESS-VAL
          SUCCESS
          MESSAGE-VAL
          MESSAGE
))