(cl:defpackage mrs_msgs-srv
  (:use )
  (:export
   "GETPATHSRV"
   "<GETPATHSRV-REQUEST>"
   "GETPATHSRV-REQUEST"
   "<GETPATHSRV-RESPONSE>"
   "GETPATHSRV-RESPONSE"
   "PATHSRV"
   "<PATHSRV-REQUEST>"
   "PATHSRV-REQUEST"
   "<PATHSRV-RESPONSE>"
   "PATHSRV-RESPONSE"
  ))

